#!/usr/bin/php
<?php

while($line = fgets(STDIN)) {
  $line = trim($line);
  $ip = process($line);
  if ($ip) {
    post($ip, $line);
  }
}

function process($line) {
  if (preg_match('/Connection closed by ([0-9.]+) \[preauth\]/', $line, $match)) {
    return $match[1];
  }
  else
  if (preg_match('/IPTables-Dropped: .* SRC=([0-9.]+) /', $line, $match)) {
    return $match[1];
  }
  else
  {
    return;
  }
}

function debug($line) {
  file_put_contents('/tmp/blackout.debug', "$line\n", FILE_APPEND);
  flush();
}

function post($ip, $title) {
  $title = preg_replace('/[^a-zA-Z0-9.,:\[\]\(\)\{\}\#+= -]/', '?', $title);
  $cmd = <<<CMD
/usr/bin/curl \
  --silent \
  --include \
  --request POST \
  --header 'Content-type: application/hal+json' \
  --header 'X-CSRF-Token: oymUgG9pPpRgmDKvyIFiISaD8IbHtQ-vi3Phk01ySq4' \
  http://dev.blackout.local:60011/entity/node?_format=hal_json \
  --data-binary '{"_links":{"type":{"href":"http://local.blackout.dev:60011/rest/type/node/item"}},"title":[{"value":"$title"}],"type":[{"target_id":"item"}],"field_source_ip":[{"value":"$ip"}]}'
CMD;
  exec($cmd);
}
