#!/usr/bin/expect

set timeout 200
set container [lindex $argv 0]

spawn docker logs -f -t "$container"
expect -re "LOG: *autovacuum launcher started"
expect -re "LOG: *autovacuum launcher started"
sleep 1
